### ISSUE TITLE
LVCSR download failed

### ISSUE THREAD

**Issue by talentoscope** [nguyenhuyanhh/magor_938_demo#11]
LVCSR server is either down or does not exist, causing a failure in the setup script.

**Comment by nguyenhuyanhh** [comment]
Hello! The server is NTU property, you need to be an approved user to access it.

Are you an NTU staff or student?

_Sent from my Google Nexus 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by talentoscope** [comment]
Hey, thanks for the reply.
I'm not, no. I didn't realise part of this project was off-limits. 
I do apologise for the error :)

**Comment by nguyenhuyanhh** [comment]
@xteejx haha no problem, in any case I should have put a comment somewhere saying it is off-limits. Will do that soon thanks!

Thanks for your interest anw!

**Comment by talentoscope** [comment]
No worries. Great projects by the way! :)

**Comment by nguyenhuyanhh** [comment]
Thank you! I moved the lvcsr system download before kaldi/sequitur installation so that the script failed immediately w/o leading to the lengthy installation of kaldi/sequitur (https://github.com/nguyenhuyanhh/magor_sgenglish/commit/4fb38afc9e6b8b52d5876d34442878d7fcbdf504), and add some notes to README (https://github.com/nguyenhuyanhh/magor_sgenglish/commit/a72875e09fac3996dda5ca8286355bcc77d08394). Consider it closed.
